-- FortifStratResDiscountAI
-- AI get discount on strategic resource needs for units
--------------------------------------------------------

-- Completely new modifier type
INSERT INTO Types (Type, Kind) VALUES
('CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'KIND_MODIFIER'),
('CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'KIND_MODIFIER');

-- New modifier we need an effect for
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
('CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_STRATEGIC_RESOURCE_REQUIREMENT_MODIFIER'),
('CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'COLLECTION_OWNER', 'EFFECT_ADJUST_PLAYER_UNIT_UPGRADE_RESOURCE_COST_DISCOUNT');

-- Add the new modifier to the pool
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, Permanent) VALUES
-- King
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_KING_DIFFICULTY', 1),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_KING_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_KING_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_KING_DIFFICULTY', 1),
-- Emperor
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_EMPEROR_DIFFICULTY', 1),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_EMPEROR_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_EMPEROR_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_EMPEROR_DIFFICULTY', 1),
-- Immortal
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_IMMORTAL_DIFFICULTY', 1),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_IMMORTAL_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_IMMORTAL_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_IMMORTAL_DIFFICULTY', 1),
-- Deity
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_DEITY_DIFFICULTY', 1),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_DEITY_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY', 'CIV_GRANT_STRAT_RES_DISCOUNT_IN_CITIES', 'AI_DEITY_DIFFICULTY', 1),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY', 'CIV_GRANT_STRAT_RES_DISCOUNT_UPGRADE_UNITS', 'AI_DEITY_DIFFICULTY', 1);

-- Arguments for our modifiert, the actual numbers
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
-- King
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING', 'Amount', '5'),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING', 'Amount', '5'),
-- Emperor
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR', 'Amount', '5'),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR', 'Amount', '5'),
-- Immortal
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL', 'Amount', '5'),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL', 'Amount', '5'),
-- Deity
('CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY', 'Amount', '5'),
('CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY', 'Amount', '5'),
('CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY', 'Amount', '5');

-- Assign the modifier to the civs as traits
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
-- King
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING'),
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_KING'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_KING'),
-- Emperor
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR'),
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_EMPEROR'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_EMPEROR'),
-- Immortal
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL'),
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_IMMORTAL'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_IMMORTAL'),
-- Deity
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY'),
('MINOR_CIV_DEFAULT_TRAIT', 'CIV_MINOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_CITY_PRODUCTION_DEITY'),
('TRAIT_LEADER_MAJOR_CIV', 'CIV_MAJOR_STRAT_RES_DISCOUNT_UNIT_UPGRADE_DEITY');
